deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
plugins:
  - opentelemetry
  - prometheus
plugin_attr:
  opentelemetry:
    resource:
      service.name: APISIX
    collector:
      address: collector:4318
  prometheus:
    export_addr:
      ip: "0.0.0.0"
